<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="author" content="Margaret K. Smith">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Instrument 16: Three Letters</title>
  <link rel="stylesheet" href="https://submissionstrategies.com/css/r2.css">
</head>

<body>
  <header>
    <?php include "../header.html" ?>
  </header>
  <main>
    <h1>Notarial Instrument 16</h1>
    <h2>Three Letters</h2>
    <h3>Submission text (English, translated by Edmund Curtis)</h3>
    <p>Notarial Instrument XVI records that: on the 5th day of March, 1394 [N.S. 1395], in a room set apart for the King in the House of the Order of Minorites in Drogheda ‘in presence of me, public notary, our lord Richard, King, &c., exhibited three letters sealed with red wax sent to him by famous Irishmen, and handed them to me, and requested me to make him a public instrument containing true copies of the aforesaid letters. The first letter was a power of proxy from Niall O’Neill, junior, captain of his nation, for doing liege homage to the said lord King, also for treating, agreeing, and concluding with Roger, Earl of March and Ulster, for certain lands by the said Niall O’Neill unjustly detained and occupied. The other two letters to the lord King from John MacDonald and Maurice [Muircheartach] Magennis, lord of Iveagh, with regard to their doing liege homage in person were brought by a faithful messenger. These letters I touched and read, the tenor of the letter of proxy being as follows:</p>
<p>‘”By these present let it appear to all that I, Niall O’Neill, junior, captain of my nation, have [174] made and ordained and appointed in my place my beloved and right worshipful father, Niall O’Neill, senior, my deputy, proxy, agent, and special envoy in these affairs, giving and granting to him general power and special mandate in my name to appear before our illustrious prince and lord, Richard, by the grace of God King of England and France, and Lord of Ireland, and before my noble lord Roger de Mortimer, Earl of March and Ulster, and to treat, agree, and conclude in my name with them and either of them or with any deputy sent by them and either of them, and to make and enter into a certain composition for obtaining and having peace to me and my nation, my subjects, and country; and if I possess any lands unjustly or harmfully or permit or make them to be occupied by others, to surrender them and all other possessions together with liberties, services, and customs whatsoever, and especially the bonnacht of the Irish of Ulster if by me or by any others in my name they are detained or occupied; also to offer, promise, and undertake sufficient amends or satisfactions for the injuries or excesses which I have wrought against the Lord our King or my lord the Earl or their lands or subjects, or have caused to be wrought or by my fault have permitted to be wrought; also to make and conclude indentures, agreements, or other writings containing any form for establishing peace and concord; and to seal and sign such writings with my seal or his own or even another for this purpose specially adapted; also firmly to bind me and my nation and country and all my goods to making and preserving peace and concord, as also [175] to undertake amends and satisfaction and to undergo temporal or spiritual punishment or ecclesiastical censures in the event, which God forbid, of this concord being violated or about to be violated; also to undertake an oath of allegiance, homage, fealty, or obedience, as far as by an agent it can be performed or done, and to take any other kind of lawful oath upon my soul, expressly renouncing every exception, whether in law or fact, whereby the effect of the intended peace and concord could be in any manner impeded or delayed, and especially renouncing all objection to the jurisdiction of the court; finally to do, dispatch, and exercise all and sundry the things which shall be necessary or even opportune to obtaining and keeping the peace of our said Lord the King and my lord the Earl. Accepting beforehand as settled and approved whatever the said N. my father and proxy shall do in my name in the above matters. In witness of which my seal is affixed to these presents. Given at Madoyn on the 6th day of January, 1394 [N.S. 1395].”</p>
<p>‘The tenor of the second letter is this:</p>
<p>‘”Most excellent Prince and my Lord King, I would have the excellence of your Majesty to know that MacDonald, Lord of the Isles, my kinsman, is and ought to be your liegeman, which MacDonald expelled me from my country even to your land of Ireland, whereupon I came to O’Neill’s country, and up to this have been sojourning with the said O’Neill in dire hardship as the world knows. But, most victorious King, if at my coming your royal Majesty had been in Ireland, I would have come to your royal [176] Majesty, but now because, not unmerited, your gracious fidelity is famed through the whole world, as is just, I am much encouraged and comforted to come to your benign presence and to be your liegeman, captain, and constable throughout all your land of Ireland with as many armed men as you wish me to have with your royal Majesty; and I wish ever to be subjected to your orders and commands, and for this purpose I offer myself as a liegeman is bound to do to his king, and if this shall be acceptable to your Majesty, if it please you, certify me of your royal Majesty through the Archbishop of Armagh, Primate of Ireland. And whether O’Neill come to your presence or not, I will come if it please your worthy excellence, even as I have informed Thomas Talbot.</p>
<p>‘”Written at Armagh, on Thursday after Ash Wednesday [25 February], your liege subject, John MacDonald, captain of his nation and constable of the Irish of Ulster.”</p>
<p>‘The tenor of the third letter is as follows:</p>
<p>“Most worshipful lord King, because I have had some talk and argument with the venerable Father and lord John, Archbishop of Armagh, Primate of Ireland, over referring and reporting divers petitions and complaints to you: in the first place, because my ancestors up to these times and in more ancient times were accustomed to hold and do now hold the whole [177] lordship of Iveagh by your authority and that of other lords, who have and had an interest therein, that is of MacKartan and of Macyleachan, Oadech, and Macyghemhna, which lordship now at present it would seem to the advantage of my lord the Earl of Ulster and of all the people that I should have and hold by your grace, paying and discharging therefor the bonnacht and all the other services and duties anciently due, and if the aforesaid things are taken from me, then from a man of good estate I should be made into one of weak and unhappy condition, which your royal Majesty would not ordain. Therefore, most excellent and noble, if [178] I ought to obtain and possess the abovesaid [lands], holding them of you and of others who have an interest therein, I will not delay to come in person to your gracious presence on a day not too soon fixed for me by pledge of the said Lord Primate and with other securities, such as your protection given under your seal patent and pendent, and your letters to be dispatched to O’Neill and Edmund ‘Saughe’, warning them under heavy penalty that after I have departed they do not harm my men, because formerly after your peace was proclaimed they did greatly harm them from both sides, and, your Majesty, believe implicitly that greater precaution is necessary with regard to securing my person than with regard to any other Irishman; on account of my brother and son who went in to Edmund Mortimer of pious memory, and neither the one nor the other ever returned. So as formerly, most excellent King, for my safety and security (profitable to me and to you) ordain a date for my appearance, if I am fortunate enough to obtain the abovesaid petitions from your grace, that is, the second Sunday of this coming Lent [7 March] or at latest the next Sunday, i.e. the third Sunday of Lent, and then I will do willing and humble liege homage, and whatever is possible for me to perform in the future you will command, and I [179] will obey my lord the Earl as is fitting. Deign to remit and return your gracious reply if it please you through my lord the Primate. I trust also you will in your justice order and command that the losses inflicted upon me, after your peace and protection had been proclaimed, by the sons of MacQuillan and other men of Edmund ‘Saughe’ and by themen of O’Neill and his brother Catholicus [Cu Uladh] and by O’Hanlon and his brothers and followers, shall be fully exacted from them and restored to the full.</p>
<p>‘”May the Omnipotent preserve you long in the noble authority which has been committed to you.</p>
<p>‘”Maurice [Muirchertach] Magennis, Lord of Iveagh thus far also and in the future by your gracious permission and free will.”’</p>
<p>Whereupon the King ordered the notary to make him a public instrument of this.</p>
<p>Witnesses: William Scrope, King’s Chamberlain, and Baldwin Bereford, knights.</p>

    <h3>Submission text (Latin, transcribed by Edmund Curtis)</h3>
    <p></p>
  </main>
  <footer>
    <?php include "../footer.html" ?>
  </footer>
</body>

</html>
